name: Jalankan Scraper Mingguan

on:
  schedule:
    - cron: '0 23 * * 0'
  workflow_dispatch:

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Tarik file Git LFS
      run: git lfs pull

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies Python
      run: pip install -r requirements.txt

    - name: Download NLTK Data
      run: |
        python -m nltk.downloader stopwords punkt wordnet

    - name: Unpack standalone Chrome + ChromeDriver
      run: |
        wget -q https://github.com/giggio/chrome-aws-lambda/releases/download/v116.0.5845.96/chrome-linux64.zip
        unzip -q chrome-linux64.zip
        export CHROME_PATH=$PWD/headless_shell
        export PATH=$PWD/chromedriver:$PATH
        chmod +x headless_shell
        chmod +x chromedriver

    - name: Run scraper
      env:
        IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        IG_APP_SECRET: ${{ secrets.IG_APP_SECRET }}
      run: |
        export CHROME_BINARY=$PWD/headless_shell
        python -u main.py
