name: Jalankan Pipeline Data Mingguan

on:
  schedule:
    - cron: '0 23 * * 0'
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode dari repository (dengan LFS)
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Tarik file dari Git LFS
        run: git lfs pull
      
      - name: Tampilkan Struktur File untuk Debugging
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install semua library yang dibutuhkan
        run: pip install -r requirements.txt

      - name: Buat file kredensial Google API dari Secrets
        env:
          GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLE_API_CREDENTIALS }}
        run: echo "$GOOGLE_API_CREDENTIALS" > google-api-credentials.json
        
      - name: Jalankan skrip utama pipeline
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_APP_SECRET: ${{ secrets.IG_APP_SECRET }}
        run: python -u main.py