name: Jalankan Scraper Mingguan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0' 

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chrome dan ChromeDriver yang Sesuai
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl jq

          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          
          CHROME_VERSION_FULL=$(google-chrome --version | awk '{print $3}')
          echo "Versi Chrome terinstall: $CHROME_VERSION_FULL"

          DRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json | jq -r ".versions[] | select(.version == \"$CHROME_VERSION_FULL\") | .downloads.chromedriver[] | select(.platform == \"linux64\") | .url")
          
          echo "Mengunduh ChromeDriver dari: $DRIVER_URL"
          wget -O chromedriver.zip "$DRIVER_URL"
          
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          echo "--- Verifikasi Instalasi ---"
          google-chrome --version
          chromedriver --version

      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Create Google API Credentials File
        env:
          GOOGLE_API_CREDENTIALS_CONTENT: ${{ secrets.GOOGLE_API_CREDENTIALS }}
        run: echo "$GOOGLE_API_CREDENTIALS_CONTENT" > google-api-credentials.json

      - name: Jalankan Scraping
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_APP_SECRET: ${{ secrets.IG_APP_SECRET }}
        run: python main.py